# Generated by Django 3.2.9 on 2024-04-23 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_sponsored'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsoredjobpost',
            old_name='date_untile',
            new_name='date_until',
        ),
    ]
